physics:
    mushroom: true
    enabled: true
    liquid: true
    sponge: true
    grass: true
    trees: true
    falling: true
    flower: true
info:
    name: OpenClassic Server
    motd: Welcome to my OpenClassic Server!
options:
    default-level: main
    port: 25565
    online-mode: true
    max-players: 20
    language: US
    public: true
    allow-flight: false
    whitelist: false
